name: Wake Up Script

on:
  schedule:
    - cron: '15 21 * * *' # Triggers at 3:15 AM IST (India is UTC+5:30 → 21:15 UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run script
        run: python wake_up_checker.py
