name: Wake Up Script

on:
  schedule:
    - cron: '45 21 * * *'  # 3:15 AM IST
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set token
        run: echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> $GITHUB_ENV

      - name: Install discord.py
        run: |
          python -m pip install --upgrade pip
          pip install discord.py

      - name: Run script
        run: python wake_up_checker.py
